// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shifts.Api.Data;

#nullable disable

namespace Shifts.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905195544_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstitutionId = 1,
                            Name = "Sucursal Central"
                        },
                        new
                        {
                            Id = 2,
                            InstitutionId = 1,
                            Name = "Sucursal Aeropuerto"
                        },
                        new
                        {
                            Id = 3,
                            InstitutionId = 2,
                            Name = "Sucursal Principal"
                        },
                        new
                        {
                            Id = 4,
                            InstitutionId = 2,
                            Name = "Sucursal Playa"
                        });
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Institution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Institutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Institucion Norte"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Institucion Sur"
                        });
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TakenAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TakenBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("TakenBy");

                    b.HasIndex("InstitutionId", "BranchId", "Priority", "CreatedAt", "Id")
                        .IsDescending(false, false, true, false, false)
                        .HasDatabaseName("IX_Shifts_PendingSelection")
                        .HasFilter("[Status] = 0");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Code = "A-001",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            InstitutionId = 1,
                            Priority = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Code = "A-002",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 5, 0, 0, DateTimeKind.Utc),
                            InstitutionId = 1,
                            Priority = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Code = "A-003",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 2, 0, 0, DateTimeKind.Utc),
                            InstitutionId = 1,
                            Priority = 5,
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Code = "B-001",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            InstitutionId = 1,
                            Priority = 3,
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 3,
                            Code = "C-001",
                            CreatedAt = new DateTime(2026, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            InstitutionId = 2,
                            Priority = 9,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InstitutionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InstitutionId = 1,
                            Name = "Ana Torres",
                            Role = "Operator"
                        },
                        new
                        {
                            Id = 2,
                            InstitutionId = 1,
                            Name = "Beto Ramirez",
                            Role = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            InstitutionId = 2,
                            Name = "Carla Nunez",
                            Role = "Operator"
                        });
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.UserBranch", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("UserBranches");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BranchId = 1
                        },
                        new
                        {
                            UserId = 2,
                            BranchId = 2
                        },
                        new
                        {
                            UserId = 3,
                            BranchId = 3
                        });
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Shifts.Api.Domain.Entities.Institution", "Institution")
                        .WithMany("Branches")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Shift", b =>
                {
                    b.HasOne("Shifts.Api.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shifts.Api.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shifts.Api.Domain.Entities.User", "TakenByUser")
                        .WithMany()
                        .HasForeignKey("TakenBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Institution");

                    b.Navigation("TakenByUser");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("Shifts.Api.Domain.Entities.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.UserBranch", b =>
                {
                    b.HasOne("Shifts.Api.Domain.Entities.Branch", "Branch")
                        .WithMany("AuthorizedUsers")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shifts.Api.Domain.Entities.User", "User")
                        .WithMany("AuthorizedBranches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Branch", b =>
                {
                    b.Navigation("AuthorizedUsers");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.Institution", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shifts.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AuthorizedBranches");
                });
#pragma warning restore 612, 618
        }
    }
}
